### ISSUE TITLE
Typography and margins

### ISSUE THREAD

**Issue by prtksxna** [prtksxna/zuari#31]

**Comment by prtksxna** [comment]
```css

  @media only screen and (max-width: 660px) {
    padding-top: 0.3rem;
    margin-bottom: 2rem;
  }
```
